name: Awesome BOT

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches: main
    paths: README.md

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  awesome-bot:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: "install awesome-bot"
        run: gem install awesome_bot
      - name: "linting: README.md"
        run: awesome_bot README.md